[package]
name = "mwf"
version = "0.1.0"
authors = ["addonovan <austin@addonovan.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
pulldown-cmark = { version = "0.0.11", deafult-features = false }

[[example]]
name = "hello_world"

[[example]]
name = "decorators"
